add_newline = false

# Prompt
format = """$username@$hostname $directory$git_branch
$character
"""
[username]
format = "[$user](181 bold)"
show_always = true

[hostname]
ssh_only = false
format = "[$hostname](white)"

[directory]
format = "[$path](111 bold)"

[git_branch]
format = '[\($branch\)](white)'

[character]
success_symbol = '[>](bold #a6d9ef)'
error_symbol = '[>](bold #ffd8ef)'



